swagger: '2.0'
info:
  description: REST API description of the ElasTest TORM Module.
  version: 1.0.0
  title: ElasTest Torm REST API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /ess
tags:
  - name: testmanagement
    description: Test Management
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: testorchestration
    description: Test Orchestation
schemes:
  - https
paths:
  /stest:
    post:
      tags:
        - Security Testing Project Creation
      summary: Create a new security testing project.
      description: Creates a new security testing project with the provided information.
      operationId: createSTProject
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Security Testing project that needs to be created
          required: true
          schema:
            $ref: '#/definitions/STProject'
      responses:
        '200':
          description: Project Created Successfully
          schema:
            $ref: '#/definitions/STProject'
        '405':
          description: Invalid input
definitions:
  STProject:
    type: object
    required:
      - name
      - vulnsToTest
    properties:
      id:
        type: integer
        format: int64
        example: '12345678'
      name:
        type: string
        example: Hello World Project
      vulnsToTest:
        type: array
        items:
          $ref: '#/definitions/STestService'
      tJob:
        type: object
        $ref: '#/definitions/TJob'
  STestService:
    type: object
    properties:
      serviceType:
        type: string
        example: userEmulator
      name:
        type: string
        example: logical
  TJob:
    type: object
    required:
      - name
      - testServices
    properties:
      id:
        type: integer
        format: int64
        example: '12345678'
      name:
        type: string
        example: testApp1
      testServices:
        type: array
        items:
          $ref: '#/definitions/TestService'
      imageName:
        type: string
        example: testapp1
      sut:
        type: integer
        example: '12345678'
  TestService:
    type: object
    properties:
      serviceType:
        type: string
        example: userEmulator
      name:
        type: string
        example: chrome
      version:
        type: integer
        format: int64
externalDocs:
  description: An elastic platform to ease end to end testing
  url: 'http://elastest.io/'
